name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - run: npm ci
      - run: npm run dev-test
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build --if-present
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain robust-crown.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

          
